name: Sign and Upload Native
description: 'Signs and uploads the native release artifacts'

inputs: 
    garasign_username:
      description: 'Garasign username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    garasign_password:
      description: 'Garasign password input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_username:
      description: 'Artifactory username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_password:
      description: 'Artifactory password input for drivers-github-tools/garasign/gpg-sign'
      required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4

    - name: Display structure of downloaded files
      run: ls -R

    - name: Get release version and release package file name
      id: vars
      shell: bash
      run: |
        package_version=$(jq --raw-output '.version' package.json)
        echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
        echo "package_file=bson-${package_version}.tgz" >> "$GITHUB_OUTPUT"