ARG PLATFORM=arm64
ARG NODE_VERSION=20.19.0

FROM ${PLATFORM}/node:${NODE_VERSION}-alpine AS build

WORKDIR /mongodb-client-encryption
COPY . .

RUN apk --no-cache add make g++ libc-dev curl bash python3 py3-pip cmake git
RUN npm run install:libmongocrypt
RUN npm run prebuild

ARG RUN_TEST
RUN if [ -n "$RUN_TEST" ]; then npm test ; else echo "skipping tests" ; fi

FROM scratch

COPY --from=build /mongodb-client-encryption/prebuilds/ /
