name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.lint-target }}
    strategy:
      matrix:
        lint-target: ["c++", "typescript"]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Build libmongocrypt"
      shell: bash
      run: |
        npm run install:libmongocrypt
        
    - if: matrix.lint-target == 'c++'
      shell: bash
      run: |
        npm run check:clang-format

    - if: matrix.lint-target == 'typescript'
      shell: bash
      run: |
        npm run check:eslint
